eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/
      #注册到服务中心
server:
  port: 9001
spring:
  application:
    name: member

  datasource:
    name: member_datasource
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/shop_member
    username: root
    password: root
    #数据源
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    in-memory: true
    pool:
      enabled: false
      #activemq
mybatis:
  type-aliases-package: com.jerry.mapper
  mapper-locations: classpath:mapping/*.xml
  config-location: classpath:mybatis-config.xml
  #mybatis配置文件